name: Buddha Bowl CI/CD Pipeline

# Define when the workflow should run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Define the jobs
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify your Node.js version here

    # Install dependencies
    - name: Install Dependencies
      run: npm install

    # Run tests
    - name: Run Tests
      run: npm run test

    # Build Nuxt App
    - name: Build Nuxt App
      run: npm run build

    # Build Storybook (if applicable)
    - name: Build Storybook
      run: npm run build-storybook
      # Add deployment commands for Storybook if needed

    # Firebase Deployment Setup (if applicable)
    - name: Setup Firebase CLI
      run: npm install -g firebase-tools

    # Deployment to Firebase (only on merge to main)
    - name: Deploy to Firebase
      if: github.ref == 'refs/heads/main'
      run: firebase deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
